# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nadctl < Formula
  desc "Control NAD audio receivers with CLI, TUI, and MCP server for LLM integration"
  homepage "https://github.com/galamiram/nadctl"
  version "1.0.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/galamiram/nadctl/releases/download/v1.0.1/nadctl_1.0.1_darwin_amd64.tar.gz"
      sha256 "c6b17da75f3e105d7eaf0a8cde4b51b73abb870530fd86209323886d72db8e4b"

      def install
        bin.install "nadctl"
      end
    end
    on_arm do
      url "https://github.com/galamiram/nadctl/releases/download/v1.0.1/nadctl_1.0.1_darwin_arm64.tar.gz"
      sha256 "6eaf13a35ff073901880619fbc4b325dae4f811bd53fce455eac3d78950685f3"

      def install
        bin.install "nadctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/galamiram/nadctl/releases/download/v1.0.1/nadctl_1.0.1_linux_amd64.tar.gz"
        sha256 "c30fe93e0d38d07092fb294ef3036ecf9303c0baab800df202757c71adf540e6"

        def install
          bin.install "nadctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/galamiram/nadctl/releases/download/v1.0.1/nadctl_1.0.1_linux_arm64.tar.gz"
        sha256 "c231207d6aba696e60e7f7cb617c04f8cc94d9fc218f8b24472176fcc8ab282c"

        def install
          bin.install "nadctl"
        end
      end
    end
  end

  test do
    system "#{bin}/nadctl --help"
  end
end
