# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nadctl < Formula
  desc "Control NAD audio receivers with CLI, TUI, and MCP server for LLM integration"
  homepage "https://github.com/galamiram/nadctl"
  version "1.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/galamiram/nadctl/releases/download/v1.2.1/nadctl_1.2.1_darwin_amd64.tar.gz"
      sha256 "b3f867a15653a883d7f958c7de8b77484e5f0c33f0c4d83410290267b829a922"

      def install
        bin.install "nadctl"
      end
    end
    on_arm do
      url "https://github.com/galamiram/nadctl/releases/download/v1.2.1/nadctl_1.2.1_darwin_arm64.tar.gz"
      sha256 "8578283290070d1324a1fd6d9763e1a09de35d04231a83d7b42e5f30e96672bb"

      def install
        bin.install "nadctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/galamiram/nadctl/releases/download/v1.2.1/nadctl_1.2.1_linux_amd64.tar.gz"
        sha256 "f348719b907f7100538d9bbf8ec4c98380acc80cc009c9c2bd2fa965e125a496"

        def install
          bin.install "nadctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/galamiram/nadctl/releases/download/v1.2.1/nadctl_1.2.1_linux_arm64.tar.gz"
        sha256 "7d78cb4a56f3f8877845c30d6771db03c1909357b7e18840f37c269eef59ae39"

        def install
          bin.install "nadctl"
        end
      end
    end
  end

  test do
    system "#{bin}/nadctl --help"
  end
end
