# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nadctl < Formula
  desc "Control NAD audio receivers with CLI, TUI, and MCP server for LLM integration"
  homepage "https://github.com/galamiram/nadctl"
  version "1.3.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/galamiram/nadctl/releases/download/v1.3.1/nadctl_1.3.1_darwin_amd64.tar.gz"
      sha256 "cbb0e0ad6cb8bf0a659766444919a550000ed87950dc25862485bd0484f8fc37"

      def install
        bin.install "nadctl"
      end
    end
    on_arm do
      url "https://github.com/galamiram/nadctl/releases/download/v1.3.1/nadctl_1.3.1_darwin_arm64.tar.gz"
      sha256 "13f94df6e9fc9295cf1ed22b99380aa9351b6861bd857a08cc6d7af85a853944"

      def install
        bin.install "nadctl"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/galamiram/nadctl/releases/download/v1.3.1/nadctl_1.3.1_linux_amd64.tar.gz"
        sha256 "fae95c1509c188d09bdf68b46350ec47bbef0dbc205bb037832a73279d3aec47"

        def install
          bin.install "nadctl"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/galamiram/nadctl/releases/download/v1.3.1/nadctl_1.3.1_linux_arm64.tar.gz"
        sha256 "ff50c0c45f7b6b122f104683334d8c12188cd52e63d13a1192e2384cf261890d"

        def install
          bin.install "nadctl"
        end
      end
    end
  end

  test do
    system "#{bin}/nadctl --help"
  end
end
